# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(577, 365)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chance = QtWidgets.QPushButton(self.centralwidget)
        self.chance.setGeometry(QtCore.QRect(230, 100, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chance.setFont(font)
        self.chance.setObjectName("chance")
        self.putin = QtWidgets.QLabel(self.centralwidget)
        self.putin.setGeometry(QtCore.QRect(10, 30, 561, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.putin.setFont(font)
        self.putin.setObjectName("putin")
        self.chance_color = QtWidgets.QPushButton(self.centralwidget)
        self.chance_color.setGeometry(QtCore.QRect(60, 210, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chance_color.setFont(font)
        self.chance_color.setObjectName("chance_color")
        self.chance_background = QtWidgets.QPushButton(self.centralwidget)
        self.chance_background.setGeometry(QtCore.QRect(400, 210, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chance_background.setFont(font)
        self.chance_background.setObjectName("chance_background")
        self.color = QtWidgets.QLabel(self.centralwidget)
        self.color.setGeometry(QtCore.QRect(20, 170, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.color.setFont(font)
        self.color.setObjectName("color")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 170, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 577, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройки"))
        self.chance.setText(_translate("MainWindow", "Изменить"))
        self.putin.setText(_translate("MainWindow", "Путь к аудиофайлe: "))
        self.chance_color.setText(_translate("MainWindow", "Изменить"))
        self.chance_background.setText(_translate("MainWindow", "Изменить"))
        self.color.setText(_translate("MainWindow", "Цвет текста: "))
        self.label_2.setText(_translate("MainWindow", "Цвет заднего фона:"))
